### ISSUE TITLE
3.0 release checklist

### ISSUE THREAD

**Issue by Veetaha** [elastio/bon#156]
These are the remaining items to be done as part of a `3.0` release.

## RC release

- [x] `#[builder(on(..., transparent))]` support  (#155)
- [x] Rename `__private` module to `__` because it  appears in error messages. Consider renaming `Unset/Set` to `UnsetMember/SetMember` to work around type qualification (#159) 
- [x] Move `#[builder(overwritable)]` under an experimental cargo feature (#160) 
- [x] Split reference docs for each atttibute parameter into separate pages (#164) 
- [x] Add support for some well-known functions in `#[builder(with)]` (#157)
    - `Some`
    - `FromIterator::from_iter` or `<_>::from_iter` 
- [x] Consider `where ...` syntax instead of `bounds(...)` in `#[builder(derive)]` (rejected, not extensible with new keys)
- [x] Update ide completions
- [x] Consider adding overwritable transitions as an extension to the API rather than replacement
- [x] Update docs 
  - [x] Typestate API. Add a guide on using the newly stable typestate API
  - [x] Alternatives update. Now it is indeed possible to extend the builder, maybe even accept by a mutable reference
  - [x] Antipattern of `impl Trait` for optional members
  - [x] Patterns/Fallible builders docs update
  - [x] Fix wording in alternatives. The count defaults example is achieveable with custom setters in typed-builder and derive_builder, but it's more attributes and syntax
  - [x] Runtime benchmarks update.
  - [x] Compilation Benchmarks 
- [x] Prepare the final changelog. Double check nothing was missed. All new/updated docs pages to the changelog

## Pre-stable release debt

- [x] Prepare a blog post
  - Show generated `rustdoc` docs comparison
  - Future plans: `#[builder(flag)]`, `#[builder(getter)]`, custom fields (`#[builder(field)]`)
  - Media idea: insert the builder type with RA type hints (comment: it's that simple)

Platforms:
  - Hackernews
  - Reddit
  - Twitter
  - LinkedIn
  - Discord servers
  - daily.dev
  - Lobste.rs
  - lemdro.id

## Post-release debt

- Automate version bumping in README (installation section)
- Add TLS termination proxy between cloudflare and website infra backend
- Proactive upgrade of some biggest OSS dependents

**Comment by pvichivanives** [comment]
Could we list which of the changes are breaking changes (maybe a [BREAKING] tag?) ? Skimming through this I don't immediately notice any breaking changes.

**Comment by Veetaha** [comment]
The changelog is not completely finished, I'm updating it lazily with each PR, but there is a penultimate item "Prepare the final changelog" in the checklist.

I already started marking things with **Breaking** on my branch. Here is the latest version of the changelog: https://github.com/elastio/bon/blob/feat/more-docs-for-v3/website/changelog.md

**Comment by Veetaha** [comment]
@pvichivanives I think I've called out all of the breaking changes in the changelog [here](https://github.com/elastio/bon/blob/feat/more-docs-for-v3/website/changelog.md?rgh-link-date=2024-10-29T19%3A52%3A07Z). However, I'll continue to extend the changelog while I document all the other non-breaking changes.

**Comment by pvichivanives** [comment]
Thank you!

**Comment by Veetaha** [comment]
`3.0.0-rc` version was published. I'll prepare a blog post for the relese and switch it to `3.0.0` on November 13-th

**Comment by Veetaha** [comment]
`3.0.0` release was published https://bon-rs.com/blog/bon-v3-release
